name: proyecto_clase
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  flutter_rating_bar: ^4.0.0
  loggy: ^2.0.3
  get: ^4.6.6
  intl: ^0.17.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker_plus: ^2.4.0

  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    # AI generated https://www.bing.com/images/create/a-tech-support-logo2c-simple-style/1-6620827393ff4bbbbb3c019fb0ea1259?id=vH%2fwI5mjcMqFK6cnzQOiAg%3d%3d&view=detailv2&idpp=genimg&thId=OIG2.xxZAQqi4EqnFzy4H1Uz7&darkschemeovr=1&edgehub=1&FORM=GCRIDP
    - assets/logo.png
    # Taken from https://unsplash.com/photos/person-using-black-computer-keyboard-08dyHxddcKc
    - assets/background.jpg
